---
    name: "release"
    
    on:
      push:
        tags:
          - "1.*"
      workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
    
    jobs:
      flutter-build-android:
        name: "Release for android"
        runs-on: "ubuntu-latest" 
        permissions: write-all
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Extract tag name
            run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            shell: bash
          - name: Echo build progress
            run: echo "Kazumi_android_${{ env.tag }}.apk build progress"
            shell: bash
          - name: Install dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libasound2-dev
            shell: bash
          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temurin'          
          - name: Set up Flutter
            uses: subosito/flutter-action@v2.16.0
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Get Flutter dependencies
            run: flutter pub get
            shell: bash
          - name: Inject DanDan API Credentials
            run: |
              sed -i "s/kvpx7qkqjh/${{ secrets.DANDANAPI_APPID }}/g" lib/utils/mortis.dart
              sed -i "s/rABUaBLqdz7aCSi3fe88ZDj2gwga9Vax/${{ secrets.DANDANAPI_KEY }}/g" lib/utils/mortis.dart
          - name: Build Flutter for Android
            run: flutter build apk --split-per-abi
            shell: bash
          - name: Package android build output
            run: cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk Kazumi_android_${env:tag}.apk
            shell: bash

          - name: Upload android outputs
            uses: actions/upload-artifact@v4
            with:
              name: android_outputs
              path: Kazumi_android_*.apk

      flutter-build-windows:
        name: "Release for windows"
        runs-on: "windows-latest"
        needs: [flutter-build-android, flutter-build-ios, flutter-build-linux, flutter-build-macos] 
        permissions: write-all
    
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - run: |
                  $tag = "${{ github.ref }}".Replace('refs/tags/', '')
                  echo "tag=$(echo $tag)" >> $env:GITHUB_ENV
          - run: echo "Kazumi_windows_${env:tag}.zip build progress"
          - run: choco install yq
          - name: Enable Git longpaths
            run: git config --system core.longpaths true
          - name: Set up Flutter
            uses: subosito/flutter-action@v2.16.0
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Set up Java
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '18'
          - run: flutter pub get
          - name: Inject DanDan API Credentials
            env:
              DANDANAPI_APPID: ${{ secrets.DANDANAPI_APPID }}
              DANDANAPI_KEY: ${{ secrets.DANDANAPI_KEY }}
            run: |
              (Get-Content -Path 'lib/utils/mortis.dart') -replace "kvpx7qkqjh", "$env:DANDANAPI_APPID" | Set-Content -Path 'lib/utils/mortis.dart'
              (Get-Content -Path 'lib/utils/mortis.dart') -replace "rABUaBLqdz7aCSi3fe88ZDj2gwga9Vax", "$env:DANDANAPI_KEY" | Set-Content -Path 'lib/utils/mortis.dart'
          - run: flutter build windows   
          - run: Compress-Archive build/windows/x64/runner/Release/* Kazumi_windows_${env:tag}.zip
          - name: Upload windows outputs
            uses: actions/upload-artifact@v4
            id: unsigned-windows-zip-artifacts
            with:
              name: windows_outputs
              path: |
                Kazumi_windows_*.zip

          # Sign Zip
          - run: New-Item -Path "build/windows/zip_signed_output" -ItemType Directory
          - name: sign windows zip
            uses: signpath/github-action-submit-signing-request@v1.1
            with:
              api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
              organization-id: 'fa047255-4772-4be1-b14f-5cfa62635877'
              project-slug: 'Kazumi'
              signing-policy-slug: 'release-signing'
              artifact-configuration-slug: 'Packet'
              github-artifact-id: '${{ steps.unsigned-windows-zip-artifacts.outputs.artifact-id }}'
              wait-for-completion: true
              output-artifact-directory: 'build/windows/zip_signed_output'
          
          - name: Upload windows zip signed ouputs
            uses: actions/upload-artifact@v4
            id: signed-windows-zip-artifacts
            with:
              name: windows_zip_signed_outputs
              path: build/windows/zip_signed_output/*.zip
              
          # Replace Unpacked Artifact with Signed Artifact
          - name: Replace Unpacked Artifact with Signed Artifact
            run: Expand-Archive -Path "build/windows/zip_signed_output/Kazumi_windows_${env:tag}.zip" -DestinationPath "build/windows/x64/runner/Release" -Force
          
          # Build Unsigned MSIX
          - name: Build unsigned msix
            run: dart run msix:create
          - name: Upload windows msix ouputs
            uses: actions/upload-artifact@v4
            id: unsigned-windows-msix-artifacts
            with:
              name: windows_msix_outputs
              path: |
                build/windows/x64/runner/Release/kazumi.msix
          
          # Sign MSIX
          - run: New-Item -Path "build/windows/msix_signed_output" -ItemType Directory
          - name: sign windows msix
            uses: signpath/github-action-submit-signing-request@v1.1
            with:
              api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
              organization-id: 'fa047255-4772-4be1-b14f-5cfa62635877'
              project-slug: 'Kazumi'
              signing-policy-slug: 'release-signing'
              artifact-configuration-slug: 'MSIX'
              github-artifact-id: '${{ steps.unsigned-windows-msix-artifacts.outputs.artifact-id }}'
              wait-for-completion: true
              output-artifact-directory: 'build/windows/msix_signed_output'
          
          - name: Upload windows msix signed ouputs
            uses: actions/upload-artifact@v4
            id: signed-windows-msix-artifacts
            with:
              name: windows_msix_signed_outputs
              path: build/windows/msix_signed_output/*.msix

      flutter-build-linux:
        name: "Release for Linux"
        runs-on: "ubuntu-latest" 
        permissions: write-all
        steps:
          - name: Clone reposit
